// Industry-specific templates for chatbots

export const industryTemplates = [
  {
    name: 'Legal Services - Law Firm',
    industry: 'legal',
    description: 'Perfect for law firms and attorneys. Qualifies potential clients and schedules consultations.',
    config: {
      enableBooking: true,
      enableQualification: true,
      collectLeads: true,
    },
    prompts: [
      "What type of legal issue are you facing?",
      "When did this incident occur?",
      "Have you consulted with an attorney before?",
      "Would you like to schedule a free consultation?",
    ],
    questions: [
      {
        id: 'legal_matter_type',
        text: 'What type of legal matter do you need help with?',
        type: 'select',
        options: ['Personal Injury', 'Family Law', 'Criminal Defense', 'Business Law', 'Estate Planning', 'Other'],
        required: true,
        score: 20,
      },
      {
        id: 'incident_date',
        text: 'When did this incident/issue occur?',
        type: 'text',
        required: false,
        score: 10,
      },
      {
        id: 'previous_attorney',
        text: 'Have you previously consulted with an attorney about this matter?',
        type: 'boolean',
        required: false,
        score: 5,
      },
      {
        id: 'timeline',
        text: 'What is your desired timeline for resolution?',
        type: 'select',
        options: ['Urgent (within 1 week)', 'Soon (1-4 weeks)', 'Flexible (1-3 months)', 'Just exploring options'],
        required: true,
        score: 20,
      },
    ],
    systemPrompt: 'You are a helpful legal assistant. Be professional, empathetic, and clear that you cannot provide legal advice but can help schedule a consultation with an attorney. Always ask about the legal matter type and timeline.',
    welcomeMessage: 'Welcome! I\'m here to help you get connected with an attorney. I\'ll ask a few questions to understand your situation and then schedule a free consultation.',
  },
  {
    name: 'Healthcare - Dental/Medical Clinic',
    industry: 'healthcare',
    description: 'For dental and medical clinics. Answers insurance questions and books appointments automatically.',
    config: {
      enableBooking: true,
      enableQualification: false,
      collectLeads: true,
    },
    prompts: [
      "What type of appointment do you need?",
      "Do you have dental/medical insurance?",
      "Are you a new or existing patient?",
      "When would you like to schedule?",
    ],
    questions: [
      {
        id: 'appointment_type',
        text: 'What type of appointment do you need?',
        type: 'select',
        options: ['General Checkup', 'Cleaning', 'Emergency', 'Follow-up', 'Consultation', 'Other'],
        required: true,
        score: 15,
      },
      {
        id: 'insurance',
        text: 'Do you have insurance?',
        type: 'boolean',
        required: true,
        score: 10,
      },
      {
        id: 'insurance_provider',
        text: 'Who is your insurance provider?',
        type: 'text',
        required: false,
        score: 10,
      },
      {
        id: 'patient_type',
        text: 'Are you a new or existing patient?',
        type: 'select',
        options: ['New Patient', 'Existing Patient'],
        required: true,
        score: 15,
      },
    ],
    systemPrompt: 'You are a friendly medical receptionist. Help patients understand services, answer insurance questions based on the practice\'s information, and book appointments. Be warm and professional.',
    welcomeMessage: 'Hi! Welcome to our practice. I can help answer questions about our services, insurance, and schedule your appointment. How can I assist you today?',
  },
  {
    name: 'Home Services - Contractors',
    industry: 'home_services',
    description: 'For contractors and repair services. Converts emergency situations into booked jobs instantly.',
    config: {
      enableBooking: true,
      enableQualification: true,
      collectLeads: true,
    },
    prompts: [
      "What type of service do you need?",
      "Is this an emergency?",
      "What's your location?",
      "When do you need this completed?",
    ],
    questions: [
      {
        id: 'service_type',
        text: 'What type of service do you need?',
        type: 'select',
        options: ['Plumbing', 'Electrical', 'HVAC', 'General Repair', 'Remodeling', 'Emergency Service', 'Other'],
        required: true,
        score: 20,
      },
      {
        id: 'emergency',
        text: 'Is this an emergency?',
        type: 'boolean',
        required: true,
        score: 30, // High score for emergencies
      },
      {
        id: 'location',
        text: 'What\'s your location/zip code?',
        type: 'text',
        required: true,
        score: 15,
      },
      {
        id: 'timeline',
        text: 'When do you need this completed?',
        type: 'select',
        options: ['Immediately', 'Within 24 hours', 'This week', 'This month', 'Flexible'],
        required: true,
        score: 20,
      },
      {
        id: 'budget',
        text: 'Do you have a budget range in mind?',
        type: 'select',
        options: ['Under $500', '$500-$1,000', '$1,000-$5,000', '$5,000-$10,000', 'Over $10,000', 'Need estimate'],
        required: false,
        score: 15,
      },
    ],
    systemPrompt: 'You are a service coordinator for a home services company. Be responsive to emergencies, gather location and service details, and book appointments quickly. Emphasize 24/7 availability for emergencies.',
    welcomeMessage: 'Hello! Need help with home repairs or services? I\'m available 24/7 to help, especially for emergencies. What can I assist you with?',
  },
  {
    name: 'Financial Services - Insurance/Advisors',
    industry: 'financial',
    description: 'For insurance agents and financial advisors. Qualifies prospects and schedules consultations.',
    config: {
      enableBooking: true,
      enableQualification: true,
      collectLeads: true,
    },
    prompts: [
      "What type of insurance/financial service are you interested in?",
      "Tell me about your current situation",
      "What are your goals?",
      "Would you like a free consultation?",
    ],
    questions: [
      {
        id: 'service_interest',
        text: 'What are you interested in?',
        type: 'select',
        options: ['Life Insurance', 'Health Insurance', 'Auto Insurance', 'Home Insurance', 'Financial Planning', 'Investment Management', 'Retirement Planning', 'Other'],
        required: true,
        score: 20,
      },
      {
        id: 'current_coverage',
        text: 'Do you currently have coverage/a financial plan?',
        type: 'boolean',
        required: false,
        score: 10,
      },
      {
        id: 'budget',
        text: 'What\'s your budget range?',
        type: 'select',
        options: ['Under $100/month', '$100-$300/month', '$300-$500/month', '$500+/month', 'Prefer to discuss'],
        required: false,
        score: 20,
      },
      {
        id: 'timeline',
        text: 'When are you looking to get started?',
        type: 'select',
        options: ['Immediately', 'Within 1 month', '1-3 months', 'Just researching'],
        required: true,
        score: 25,
      },
    ],
    systemPrompt: 'You are a professional financial services assistant. Build trust, understand client needs and goals, and guide them toward booking a free consultation. Be knowledgeable but avoid giving specific financial advice.',
    welcomeMessage: 'Welcome! I\'m here to help you find the right insurance or financial solution for your needs. Let\'s start with a few questions, and then I can schedule a free consultation with one of our advisors.',
  },
  {
    name: 'Real Estate - Agents',
    industry: 'real_estate',
    description: 'For real estate agents. Provides instant property info and connects buyers with agents.',
    config: {
      enableBooking: true,
      enableQualification: true,
      collectLeads: true,
    },
    prompts: [
      "Are you looking to buy or sell?",
      "What type of property?",
      "What's your location preference?",
      "What's your budget/price range?",
    ],
    questions: [
      {
        id: 'intent',
        text: 'Are you looking to buy or sell a property?',
        type: 'select',
        options: ['Buy', 'Sell', 'Both', 'Just browsing'],
        required: true,
        score: 20,
      },
      {
        id: 'property_type',
        text: 'What type of property?',
        type: 'select',
        options: ['Single Family Home', 'Condo/Townhouse', 'Multi-family', 'Land', 'Commercial', 'Other'],
        required: true,
        score: 15,
      },
      {
        id: 'location',
        text: 'What area/neighborhood are you interested in?',
        type: 'text',
        required: true,
        score: 15,
      },
      {
        id: 'budget',
        text: 'What\'s your budget range?',
        type: 'select',
        options: ['Under $200k', '$200k-$400k', '$400k-$600k', '$600k-$800k', '$800k-$1M', 'Over $1M'],
        required: true,
        score: 25,
      },
      {
        id: 'timeline',
        text: 'What\'s your timeline?',
        type: 'select',
        options: ['Ready now', '1-3 months', '3-6 months', '6+ months', 'Just researching'],
        required: true,
        score: 25,
      },
    ],
    systemPrompt: 'You are a helpful real estate assistant. Help visitors find properties, answer questions about listings, and connect them with agents. Be knowledgeable about the market and enthusiastic about helping them find their dream home.',
    welcomeMessage: 'Hi! Looking for your next home or ready to sell? I can help you search properties, answer questions, and connect you with one of our top agents. What brings you here today?',
  },
  {
    name: 'B2B Services - Consultants/Agencies',
    industry: 'b2b',
    description: 'For B2B consultants and agencies. Qualifies prospects and books discovery calls automatically.',
    config: {
      enableBooking: true,
      enableQualification: true,
      collectLeads: true,
    },
    prompts: [
      "What challenges is your business facing?",
      "Tell me about your company",
      "What's your timeline for a solution?",
      "Would you like to schedule a discovery call?",
    ],
    questions: [
      {
        id: 'company_size',
        text: 'How many employees does your company have?',
        type: 'select',
        options: ['1-10', '11-50', '51-200', '201-500', '500+'],
        required: true,
        score: 15,
      },
      {
        id: 'industry',
        text: 'What industry is your company in?',
        type: 'text',
        required: true,
        score: 10,
      },
      {
        id: 'challenge',
        text: 'What\'s the main challenge you\'re looking to solve?',
        type: 'text',
        required: true,
        score: 20,
      },
      {
        id: 'budget',
        text: 'What\'s your approximate budget for this project?',
        type: 'select',
        options: ['Under $10k', '$10k-$25k', '$25k-$50k', '$50k-$100k', '$100k+', 'Need to discuss'],
        required: false,
        score: 25,
      },
      {
        id: 'decision_maker',
        text: 'Are you the decision maker for this project?',
        type: 'boolean',
        required: true,
        score: 30,
      },
    ],
    systemPrompt: 'You are a professional business development assistant for a B2B consulting/agency firm. Ask qualifying questions to understand company size, challenges, budget, and decision-making authority. Guide qualified prospects toward booking a discovery call.',
    welcomeMessage: 'Welcome! We help businesses like yours solve complex challenges. I\'d like to learn more about your needs so I can connect you with the right specialist. Shall we get started?',
  },
]

export function getTemplateByIndustry(industry: string) {
  return industryTemplates.find((t) => t.industry === industry)
}

export function getAllTemplates() {
  return industryTemplates
}
